#     {"name":"","artist":,"cosmo":,"mathe":,"female":,"rel":,"famous":,"inventor":,"physi":,"au":,"austrailian":,"american":,"british":,"aisian":,"undereightteen":,"alive":,"movie":,"saint":,"overtwenseve":,"theorist":,"streamer":,"youtuber":,"real":},

database = [

    {"name":"Albert Einstein","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":True,"physi":True,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":False,"movie":False,"saint":False,"overtwenseve":True,"theorist":True,"streamer":False,"youtuber":False,"real":True},
    {"name":"Isaac Newton","artist":False,"cosmo":False,"mathe":True,"female":False,"rel":False,"famous":True,"inventor":True,"physi":True,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":False,"movie":False,"saint":False,"overtwenseve":True,"theorist":True,"streamer":False,"youtuber":False,"real":True},
    {"name":"Steven Hawking","artist":False,"cosmo":True,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":True,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":False,"movie":False,"saint":False,"overtwenseve":True,"theorist":True,"streamer":False,"youtuber":False,"real":True},
    {"name":"Sssniperwolf","artist":False,"cosmo":False,"mathe":False,"female":True,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":True,"real":True},
    {"name":"Fairbairn Films","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":True,"american":False,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":True,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":True,"real":True},
    {"name":"Trycs","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":False,"british":False,"aisian":False,"undereightteen":True,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":True,"real":True},
    {"name":"Dhar Mann","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":True,"saint":False,"overtwenseve":True,"theorist":False,"streamer":False,"youtuber":True,"real":True},
    {"name":"Technoblade","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":True,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":True,"youtuber":True,"real":True},
    {"name":"Ph1LzA","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":False,"british":True,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":True,"theorist":False,"streamer":True,"youtuber":False,"real":True},
    {"name":"Ranboo","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":False,"famous":True,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":True,"british":True,"aisian":False,"undereightteen":True,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":True,"youtuber":True,"real":True},
    {"name":"Your Aunt","artist":False,"cosmo":False,"mathe":False,"female":True,"rel":True,"famous":False,"inventor":False,"physi":False,"au":True,"austrailian":False,"american":False,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":False,"real":True},
    {"name":"Your Uncle","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":True,"famous":False,"inventor":False,"physi":False,"au":True,"austrailian":False,"american":False,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":False,"real":True},
    {"name":"Your Sister","artist":False,"cosmo":False,"mathe":False,"female":True,"rel":True,"famous":False,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":False,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":False,"real":True},
    {"name":"Your Brother","artist":False,"cosmo":False,"mathe":False,"female":False,"rel":True,"famous":False,"inventor":False,"physi":False,"au":False,"austrailian":False,"american":False,"british":False,"aisian":False,"undereightteen":False,"alive":True,"movie":False,"saint":False,"overtwenseve":False,"theorist":False,"streamer":False,"youtuber":False,"real":True},

]